<?php
echo "<h1>You opened Door 3!: The Last Ember of the Arcane</h1>";
echo "<p>In the kingdom of Mardor, where magic once thrived, the Order of the Ember guarded the secrets of the Arcane. Their power came from the Last Ember, a flame gifted by the gods, kept alive by the wizards' magic. But a dark sorcerer named Malvor had discovered a forbidden spell, one capable of extinguishing the Ember and wiping out all magic from the world.</p>"
echo "<p>Rhiannon, the youngest member of the Order, felt a special connection to the Ember. She often visited its chamber, drawn to its mysterious power. One evening, as she stood before the flame, she sensed something was wrong. The Ember flickered and dimmed, sending a chill through the room as if something dark was drawing near.</p>"
echo "<p>That night, Rhiannon overheard her mentor, Master Vaelan, discussing Malvor. The rogue sorcerer, long thought dead, had returned. With his newfound knowledge of the forbidden spell, he planned to destroy the Ember. The wizards of the Order were powerless to stop him, and only Rhiannon could hope to prevent the disaster.</p>"
echo "<p>Determined to protect the Ember, Rhiannon left the citadel on her own. Armed with little more than her dagger and the ancient knowledge she had studied, she traveled through dangerous lands—illusion-filled swamps, fire-breathing mountains, and haunted forests. Every step brought her closer to Malvor’s dark citadel.</p>"
echo "<p>After days of peril, she arrived at the Black Citadel, where Malvor waited. The air was thick with dark magic as he stood before the Ember, encased in a crystal orb. “You cannot stop me,” Malvor sneered. “The Ember will be mine.”</p>"
echo "<p>Rhiannon, gathering all her strength, summoned the last of the Ember’s power. Flames clashed with darkness in a fierce battle. The Ember flickered weaker with every strike, but Rhiannon, remembering the magic her mother had once taught her, called forth a spell of pure intent. It was enough to imprison Malvor in the very shadows he had tried to control.</p>"
echo "<p>As the darkness faded, Malvor was sealed away. The Ember blazed brightly once more, its power restored. Rhiannon returned to the Order, hailed as a hero. But as she looked into the flame, she knew her journey was far from over. As long as the Ember lived, there would always be those who sought to control it. And she would be ready.</p>"
?>